spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  datasource:
    url: jdbc:postgresql://lec2-23-23-182-238.compute-1.amazonaws.com:5432/d9p5k4276iosco
    username: jcnsrhprgibddb
    password: 178f04e4a1d3b544974b941fe0ac191dbb5ba60492cda12a6ef4d84f35207b3ae
---
logging:
  level:
    org:
      springframework:
        web: DEBUG
---
management:
  endpoints:
    web:
      exposure:
        include: *